### ISSUE TITLE
Sites that require JS do not work

### ISSUE THREAD

**Issue by alexolog** [Quicksaver/AutoPager#1]
In particular, Google's "search by image".
Example: http://tinyurl.com/kopgxvx

**Comment by Quicksaver** [comment]
Google's search by image actually hasn't worked for me for a long time now. But I'll take a look into it and see if I can do anything about it.

**Comment by alexolog** [comment]
Fixed.  Please pull

**Comment by Quicksaver** [comment]
Pushed a 0.8.0.8.2 release with your patch at https://github.com/Quicksaver/AutoPager/releases

**Comment by Quicksaver** [comment]
Apparently Wind Li hasn't given up on AutoPager just yet. Maybe it would be better if you suggested your fixes to him directly, as he didn't include any of them in 0.8.0.10
